### ISSUE TITLE
No death penalty

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#124]
Upon dying and respawning, I've noticed that you never really lose exp or regain hp or wounds. I don't know if you guys already knew this, but I think it is necessary to bring up this issue again since re-spawning with 95% wounds and no refund, is sort of painful right now. Btw, good job on implementing the wounds! ^^

**Comment by exectails** [comment]
Is there a list of penalties and how much life you regain somewhere?

**Comment by Cosrnos** [comment]
@exectails I believe I fixed this on the old old OLD dungeon branch and never thought to merge it in. Might be worth checking out

**Comment by exectails** [comment]
@Cosrnos Provided that branch still exists somewhere =< Did you have the correct penalties? Because I just saw that the data on the Wiki is either complete nonsense or outdated.

**Comment by Cosrnos** [comment]
I thought I did. However if the wiki data is outdated or incorrect then I will say no :grin:

**Comment by Xcelled** [comment]
Just grab it out of the lang files, I know the client is correct at least!

**Comment by exectails** [comment]
It's a formula o,o

**Comment by Xcelled** [comment]
I thought the actual percents were in the client text, but it's been forever since I paid attention to those, so...

Actually wait, doesn't hovering over the buttons tell you how much exp you're going to lose or something?

**Comment by exectails** [comment]
Yes, but the localization basically works like C# string.format, there are {0} placeholders. I haven't looked, but I highly doubt that there are x phrases, for every possibility, especially seeing how the exp value seemingly changes every level =<

**Comment by Xcelled** [comment]
Well at the least, then, you can quickly take some samples in Aura instead of having to die in NA...

**Comment by exectails** [comment]
Well, yes, but samples don't really help me if it's not a very simple formula. It doesn't seem to be a multiplier, as the Wiki suggests =/

**Comment by Xcelled** [comment]
It's probably some type of exponential to match the levelup exp? Maybe a multiplier *of* the level up exp? Take a dozen samples and plot them :D

**Comment by exectails** [comment]
That sounds really, *really* boring =< You do that =D

**Comment by exectails** [comment]
Took a look a closer look at an older client, apparently the Wiki was right, at some point, at least partially. But the current penalties are way lower than what the Wiki and the old client list, so I assume the penalties were changed semi-recently =/

**Comment by ImaBrokeDude** [comment]
How does one test this? Maybe I can throw some stuff in the research stuff on the forum.

**Comment by exectails** [comment]
There's nothing to test, we simply need formulas.

**Comment by exectails** [comment]
**Formula**
`requiredExp * multiplier * range`

Based on what the client displayed for various revive options on different levels and some playing around with the numbers. Seems to work perfectly. `requiredExp` is the amount of exp required to reach the next level (*not* the *total* exp). E.g.: 1300 for Level 4.

**Multipliers**
Revive Here: `0.01`
Wait for Rescue: `0.0025`
Dungeon Entrance: `0.0050`
Statue of Goddess: `0.0075`

**Range**
Level 1~9: `1`
Level 10~29: `3`
Level 30~49: `4`
Level 50~99: `5`
Level 100~200: `6`

**Comment by DeleteIT** [comment]
What's the Nao multiplier?

**Comment by exectails** [comment]
>What's the Nao multiplier?

Oh, forgot about her, because the option doesn't appear until you have stones. Added it, it's `0.001`.

>removes the experience loss from reviving in town.

Oh... that might explain why I've seen only 0 loss on Town revive =P" Added that one as well: `0.005`.
