### ISSUE TITLE
Unable to learn 'Handicraft'

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#60]
I tried to learn Handicraft before this skill was even added and got a nothing useful from the book except from a novice skill rank.  After the skill was added I purchased a new book with a new seal, it disappears and I still can't learn how to use the skill. 

![capture](https://cloud.githubusercontent.com/assets/13089450/10925805/acb3bb66-8291-11e5-9a4a-47735d9360e0.PNG)

**Comment by exectails** [comment]
Should be fixed now, after this commit: https://github.com/aura-project/aura/commit/3d53ebd0b10974927e754bf96043598a1dd4c80a

**Comment by Pegwald** [comment]
This didn't fix my issue, really. I purchased a new book, but nothing happened after reading the seal off.  I'm still at novice, not able to use or learn the skill.

**Comment by exectails** [comment]
Oh, you're right, QweQwe forgot something. *Now* it is fixed^^

**Comment by Pegwald** [comment]
That's right! You're the best :>
